# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

contains <- function(str, substr) {
    .Call('microarrayTools_contains', PACKAGE = 'microarrayTools', str, substr)
}

searchDesc <- function(desc, searchTerms) {
    .Call('microarrayTools_searchDesc', PACKAGE = 'microarrayTools', desc, searchTerms)
}

containsString <- function(str, substr) {
    .Call('microarrayTools_containsString', PACKAGE = 'microarrayTools', str, substr)
}

searchDescReturnHits <- function(desc, searchTerms) {
    .Call('microarrayTools_searchDescReturnHits', PACKAGE = 'microarrayTools', desc, searchTerms)
}

