# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

contains <- function(str, substr) {
    .Call('_microarrayTools_contains', PACKAGE = 'microarrayTools', str, substr)
}

searchDesc <- function(desc, searchTerms) {
    .Call('_microarrayTools_searchDesc', PACKAGE = 'microarrayTools', desc, searchTerms)
}

containsString <- function(str, substr) {
    .Call('_microarrayTools_containsString', PACKAGE = 'microarrayTools', str, substr)
}

searchDescReturnHits <- function(desc, searchTerms) {
    .Call('_microarrayTools_searchDescReturnHits', PACKAGE = 'microarrayTools', desc, searchTerms)
}

